version: "3"

services:

# ------> kibana ------>
    kibana_347089:
        container_name: kibana_347089
        # see https://www.docker.elastic.co/
        # see https://www.elastic.co/guide/en/kibana/6.6/docker.html
        image: docker.elastic.co/kibana/kibana:6.6.2
        restart: 'on-failure'
        environment:
            ELASTICSEARCH_URL: http://elasticsearch_744301:9200
        ports:
            - 5601:5601
        volumes:
            - ./kibana/config:/usr/share/kibana/config
# <------ kibana <------

# ------> elasticsearch ------>
    elasticsearch_744301:
        container_name: elasticsearch_744301
        # see https://www.docker.elastic.co/
        # see https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        restart: 'on-failure'
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            #ELASTIC_PASSWORD: root
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
            - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
            - .././skyflow/database/elasticsearch:/usr/share/elasticsearch/data
# <------ elasticsearch <------